name: dart_geohash
description: A simple encode, decode, and neighbor finder for longitude/latitude and geohash.
version: 0.0.1
author: Nicholas Frawley
homepage: https://unbasedstudios.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec