name: dart_geohash
description: A simple encode, decode, and neighbor finder for longitude/latitude and geohash.
version: 1.0.0
author: Nicholas Frawley <nfrawley93@gmail.com>
homepage: https://nicholasfrawley.com
repository: https://github.com/nfrawley93/dart_geohash

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter